services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ./tsp-output/@typespec/openapi3:/schema
    environment:
      SWAGGER_JSON: /schema/openapi.yaml
    restart: always
  redocly:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: redocly
    ports:
      - 127.0.0.1:8082:8080
    volumes:
      - ./tsp-output/@typespec/openapi3:/schema
    environment:
      SPEC_URL: /schema/openapi.yaml
    restart: always
    init: true
