version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./schema:/work
    environment:
      SWAGGER_JSON: /work/openapi.yml
    restart: always
  redocly:
    image: redocly/redoc
    container_name: redocly
    ports:
      # 80番ポートでないとファイルの変更を反映してくれない
      - 80:80
    volumes:
      - ./schema:/usr/share/nginx/html/api
    environment:
      SPEC_URL: api/openapi.yml
    restart: always
