version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ./schema:/schema
    environment:
      SWAGGER_JSON: /schema/openapi.yml
    restart: always
  redocly:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: redocly
    ports:
      - 127.0.0.1:8082:8080
    volumes:
      - ./schema:/schema
    environment:
      SPEC_URL: /schema/openapi.yml
    restart: always
