parameters:
  id:
    name: formId
    in: path
    description: フォームID
    required: true
    schema:
      $ref: "./components.yml#/components/schemas/id"
  form_title:
    name: title
    in: query
    description: フォームのタイトル
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/title"
  form_description:
    name: description
    in: query
    description: フォームの説明
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/description"
  start_at:
    name: startAt
    in: query
    description: |
      フォームの回答期間の開始日。
      この開始日は回答可能期間に含まれます。
      終了日(`end_at`)が指定されていない場合は失敗する可能性があります。
      新たに設定する場合は`start_at`と`end_at`の両方を含めたパラメータを指定してください。
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/start_at"
  end_at:
    name: endAt
    in: query
    description: |
      フォームの回答期間の終了日。
      この終了日は回答可能期間に含まれます。
      開始日(`start_at`)が指定されていない場合は失敗する可能性があります。
      新たに設定する場合は`start_at`と`end_at`の両方を含めたパラメータを指定してください。
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/end_at"
  webhook_url:
    name: webhook
    in: query
    description: フォームの変更などを通知するリンク
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/webhook_url"
  default_title:
    name: defaultTitle
    in: query
    description: |
      各回答に対してつけられるタイトル。
      $[question_id]と指定することで質問のquestion_idに対応する回答を埋め込むことができます。
      デフォルト値: 未設定
    required: false
    schema:
      $ref: "./components.yml#/components/schemas/default_title"
  form_label_target:
    name: target
    in: query
    required: true
    description: 何に対してのラベルを取得するかを取得するか。
    schema:
      $ref: "./components.yml#/components/schemas/kind_of_labels"
