parameters:
  id:
    name: formId
    in: path
    description: フォームID
    required: true
    schema:
      $ref: './components.yml#/components/schemas/id'
  form_title:
    name: formTitle
    in: query
    description: フォームのタイトル
    required: false
    schema: 
      $ref: './components.yml#/components/schemas/title'
  form_description:
    name: formDescription
    in: query
    description: フォームの説明
    required: false
    schema: 
      $ref: './components.yml#/components/schemas/description'
  start_at:
    name: startAt
    in: query
    description: |
      フォームの回答期間の開始日。
      終了日(`end_at`)が指定されていない場合は失敗する可能性があります。
      新たに設定する場合は`start_at`と`end_at`の両方を含めたパラメータを指定してください。
    required: false
    schema: 
      $ref: './components.yml#/components/schemas/start_at'
  end_at:
    name: endAt
    in: query
    description: |
      フォームの回答期間の終了日。
      開始日(`start_at`)が指定されていない場合は失敗する可能性があります。
      新たに設定する場合は`start_at`と`end_at`の両方を含めたパラメータを指定してください。
    required: false
    schema: 
      $ref: './components.yml#/components/schemas/end_at'
  form_label_target:
    name: target
    in: query
    required: true
    description: 何に対してのラベルを取得するかを取得するか。
    schema:
      $ref: './components.yml#/components/schemas/kind_of_labels'
