name: Lint and Publish OpenAPI Documents
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint-openapi.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install redocly-cli
        uses: ./.github/actions/install-redocly-cli
      - name: Build docs
        run: redocly build-docs ./schema/openapi.yml -o ./docs/index.html -t ./.github/template.hbs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs
  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
